Feature/kustomize implementation
ZupIT/charlescd-operator pull request #22
Opened 2022-03-25 11:24 UTC by kelsoncarmozinezup

2022-03-31 14:03 UTC, thallesfreitaszup commented on internal/client/kustomization.go
> +func (k *Kustomization) Template(ctx context.Context, source, path string) (mf.Manifest, error) {
Isn't Kustomize a more semantic name than Template? I think  template is more related to helm than kustomize.

2022-03-31 14:03 UTC, thallesfreitaszup commented on pkg/module/kustomization_validation.go
> +	log.Info("kustomizationValid")
same here

2022-04-01 13:00 UTC, tiagoangelozup commented on internal/client/kustomization.go
> +func (k *Kustomization) template(filePath string) (resmap.ResMap, error) {
I tried to create a module with the below resource:
```yaml
apiVersion: deploy.charlescd.io/v1alpha1
kind: Module
metadata:
  name: football-bets
kustomization:
  gitRepository:
    path: deploy
    ref:
      type: commit
      value: bcf5f8101a1ef433013152ac89b3502b58234365
    url: https://github.com/tiagoangelozup/football-bets
```
but I got the following error
```yaml
status:
  conditions:
    - lastTransitionTime: "2022-04-01T12:30:48Z"
      message: Sources available locally at /tmp/gitrepository/kuttl-test-worthy-escargot/football-bets/bcf5f8101a1ef433013152ac89b3502b58234365.tar.gz
      reason: Downloaded
      status: "True"
      type: SourceReady
    - lastTransitionTime: "2022-04-01T12:30:48Z"
      message: 'erro running kustomizer: %!w(<nil>)'
      reason: RenderError
      status: "False"
      type: SourceValid
  phase: Failed
  source:
    path: /tmp/gitrepository/kuttl-test-worthy-escargot/football-bets/bcf5f8101a1ef433013152ac89b3502b58234365.tar.gz
```
here are some logs [charlescd.log](https://github.com/ZupIT/charlescd-operator/files/8397862/charlescd.log)

2022-04-05 12:25 UTC, kelsoncarmozinezup commented on internal/client/kustomization.go
> +func (k *Kustomization) Template(ctx context.Context, source, path string) (mf.Manifest, error) {
Changed to kustomize.

2022-04-05 12:26 UTC, kelsoncarmozinezup commented on pkg/module/helm_validation.go
> +	log.Info("HelmValid")
Log removed.

2022-04-05 12:26 UTC, kelsoncarmozinezup commented on pkg/module/kustomization_validation.go
> +	log.Info("kustomizationValid")
Log removed.

2022-04-05 12:27 UTC, kelsoncarmozinezup commented on go.mod
> +	sigs.k8s.io/kustomize/kustomize/v4 v4.4.1
Updated libraries.

2022-04-05 12:28 UTC, kelsoncarmozinezup commented on internal/client/kustomization.go
> +func (k *Kustomization) template(filePath string) (resmap.ResMap, error) {
Bug fixed.

2022-04-05 12:48 UTC, thallesfreitaszup submitted a review, later dismissed

2022-04-06 13:52 UTC, tiagoangelozup commented on go.mod
>  	k8s.io/apiextensions-apiserver v0.23.4
usually `k8s.io/apiextensions-apiserver` match the same versions of `k8s.io/apimachinery` and `k8s.io/client-go`.

2022-04-06 13:52 UTC, tiagoangelozup commented on pkg/module/kustomization_validation.go
> +	kustomizationValid       = "Kustomize configurations is valid"
"Kustomize configurations **are** valid"

2022-04-06 14:20 UTC, barbararochazup requested changes
Add a pull request description

2022-04-06 16:29 UTC, tiagoangelozup approved these changes

2022-04-07 14:14 UTC, barbararochazup submitted a review, later dismissed

2022-04-12 12:13 UTC, tiagoangelozup submitted a review, later dismissed

2022-04-12 12:30 UTC, thallesfreitaszup approved these changes

2022-04-12 17:46 UTC, tiagoangelozup approved these changes

2022-04-12 18:47 UTC, barbararochazup approved these changes

2022-04-12 18:47 UTC, merged