pure manifest integration tests
ZupIT/charlescd-operator pull request #26
Opened 2022-04-01 17:54 UTC by thallesfreitaszup

Signed-off-by: Thalles Freitas <thalles.freitas@zup.com.br>

2022-04-01 20:11 UTC, angelicalimazup approved these changes

2022-04-06 12:25 UTC, tiagoangelozup approved these changes

2022-04-06 14:22 UTC, barbararochazup requested changes
Add a pull request description

2022-04-07 14:04 UTC, barbararochazup approved these changes

2022-04-07 14:20 UTC, angelicalimazup approved these changes

2022-04-07 14:23 UTC, merged